/**Problem 2 from projectEuler.net 
 * Posted 19 October 2001
 * Solution by Kyle Chamberlin
 * Solved 12 July 2012
 * Problem 2 is stated as :
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

package projectEuler;

public class Problem40 {

	long answer = 1;
	/**
	 * 
	 * @param args
	 */
	public Problem40(){
		int[] digits = concatNum(1000000);
		for(int i = 1; i <= 1000000; i *=10){
			answer *= digits[i];
		}
	}
	
	public long getAnswer(){
		return answer;
	}
	
	private int[] concatNum(int pN){
		int[] array = new int[pN+2];
		int digits = 0;
		for(int i = 0; digits < pN + 1 ; i++){
			String breakMe = "" + i;
			for(int a = 0; digits < array.length && a < breakMe.length(); a++){
				array[digits] = breakMe.charAt(a) - 48;
				digits++;
			}
		}
		return array;
	}
	
	
}
