/**Problem 2 from projectEuler.net 
 * Posted 19 October 2001
 * Solution by Kyle Chamberlin
 * Solved 12 July 2012
 * Problem 2 is stated as :
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

package com.kylechamberlin.projectEuler.solutions;

public class Problem28 {

	int answer = 1;

	public Problem28(){
		int add = 1;
		for(int size = 3; size <= 1001; size+=2){
			for(int i = 0; i < 4 ; i++){
				add += size - 1;
				answer += add;
			}
		}
	}
	
	public int getAnswer(){
		return answer;
	}
	
	
}
